In [130]:
import numpy as np
import pandas as pd
from sklearn.linear_model import LinearRegression
from sklearn.svm import SVR
from sklearn.linear_model import LogisticRegression
from sklearn.feature_extraction.text import CountVectorizer
from sklearn import svm
from sklearn.ensemble import RandomForestRegressor
from sklearn.neighbors import KNeighborsRegressor
from sklearn.metrics import explained_variance_score
from sklearn.metrics import accuracy_score

In [2]:
np.set_printoptions(precision=2)

In [3]:
data = pd.read_csv('final_cars_datasets_1.csv', error_bad_lines=False)

**Сведем эту таблицу к данным, имеющим одинаковую марку, модель, год, трансмиссию и т.д. Различия в этих данных будут заключаться только в пробеге и цене.**


In [161]:
hd=data[(data["mark"] == "honda") &(data["model"] == "fit")& (data["transmission"] == "at") & (data["year"] == 2005) & (data["engine_capacity"] == 1300) & (data["drive"]=="2wd")]

In [162]:
hd

Unnamed: 0  price   mark model  year  mileage  engine_capacity  \
255          259    569  honda   fit  2005   116000             1300   
316          320    616  honda   fit  2005   108200             1300   
393          397    655  honda   fit  2005   105892             1300   
610          617    790  honda   fit  2005    99000             1300   
620          627    790  honda   fit  2005    90000             1300   
628          635    790  honda   fit  2005    81000             1300   
968          976    933  honda   fit  2005    59475             1300   
1485        1501   1120  honda   fit  2005    36000             1300   

     transmission drive hand_drive      fuel  
255            at   2wd        rhd  gasoline  
316            at   2wd        rhd  gasoline  
393            at   2wd        rhd  gasoline  
610            at   2wd        rhd  gasoline  
620            at   2wd        rhd  gasoline  
628            at   2wd        rhd  gasoline  
968            at   2wd        rhd  gasoline  
1485           at   2wd        rhd  gasoline

In [163]:
x=np.array(hd["mileage"]).reshape((-1,1))
y=np.array(hd["price"])

In [164]:
y

array([ 569,  616,  655,  790,  790,  790,  933, 1120], dtype=int64)

## Линейная регрессия ##

In [165]:
model = LinearRegression()

In [166]:
model.fit(x, y)

LinearRegression()

In [167]:
r_sq = model.score(x, y)
print('coefficient of determination:', r_sq)

coefficient of determination: 0.9499656712534658


In [168]:
#print('intercept:', model.intercept_)

In [169]:
#print('slope:', model.coef_)

In [170]:
y_pred = model.predict(x)
print('predicted response:', y_pred, sep='\n')

predicted response:
[ 595.98  646.15  661.    705.33  763.23  821.12  959.59 1110.59]


## Метод опорных векторов ##

In [171]:
opvec = SVR()
opvec.fit(x, y)
y_pred = opvec.predict(x)
#accuracy = model.score(x, y)
print('predicted response:', y_pred, sep='\n')
#print("Точность метода опорных векторов:", accuracy)

predicted response:
[788.19 788.39 788.52 789.03 789.73 790.27 791.3  791.5 ]


## Логистическая регрессия ##

In [172]:
logic = LogisticRegression(max_iter = 10000)
logic.fit(x, y);
y_pred = logic.predict(x)
print('predicted response:', y_pred, sep='\n')


predicted response:
[790 790 790 790 790 790 790 790]


## Дополнительный метод ##

In [175]:
forest = RandomForestRegressor()
forest.fit(x, y)
y_pred = forest.predict(x)
print('predicted response:', y_pred, sep='\n')


predicted response:
[ 584.83  622.94  658.69  756.35  785.95  791.51  916.5  1029.47]
